"""VideoContinuityManager — cross-clip last-frame anchoring (Sprint 1 P1-3).

Foundation for the multi-clip stitching path that unlocks S5 30/60/90s VLOG
durations (P1-4). The same anchoring solves S4's "AI clip jump cut" risk from
the diagnostic (R-S4-CONT).

Workflow:
    1. Clip N is generated by Seedance via SeedanceClient.
    2. VideoContinuityManager.extract_last_frame(clip_N) → frame.png
    3. Clip N+1 is generated with `continuity_frame_path=frame.png` so that
       image_to_video uses it as the first-frame guidance, producing a
       visually-continuous transition.

This module shells out to ffmpeg (already a project dep — see
Dockerfile.backend / Lighthouse). Operation is pure (no network, no LLM).
"""

from __future__ import annotations

import asyncio
import os
from pathlib import Path
from typing import Any

import structlog

from src.skills.base import SkillCallable, SkillResult
from src.skills.registry import SkillRegistry

logger = structlog.get_logger()


async def extract_last_frame(
    video_path: Path | str,
    output_dir: Path | str | None = None,
    quality: int = 2,
) -> Path:
    """Extract the last frame of `video_path` as a PNG via ffmpeg.

    Args:
        video_path: Path to source mp4/mov/etc.
        output_dir: Where to write the frame. Defaults to video_path.parent.
        quality: ffmpeg -q:v value (1=best, 31=worst; 2 is visually lossless).

    Returns:
        Path to the extracted PNG.

    Raises:
        FileNotFoundError: video_path missing or empty.
        RuntimeError: ffmpeg failed (non-zero exit or no output produced).
    """
    src = Path(video_path)
    if not src.exists() or src.stat().st_size == 0:
        raise FileNotFoundError(f"VideoContinuityManager: source missing: {src}")

    dest_dir = Path(output_dir) if output_dir else src.parent
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / f"{src.stem}_last_frame.png"

    # ffmpeg incantation: -sseof -1 seeks 1s from end of file, then we grab
    # the very last frame via -update 1 -frames:v 1. -y overwrites existing
    # output. -q:v controls PNG quality (preserved via -compression_level 0
    # if available, else implicit).
    cmd = [
        "ffmpeg",
        "-y",
        "-sseof", "-1",
        "-i", str(src),
        "-update", "1",
        "-frames:v", "1",
        "-q:v", str(quality),
        str(dest),
    ]

    logger.debug("video_continuity: extracting last frame", source=str(src), dest=str(dest))

    proc = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.DEVNULL,
        stderr=asyncio.subprocess.PIPE,
    )
    _, stderr = await proc.communicate()

    if proc.returncode != 0:
        err = stderr.decode("utf-8", errors="replace")[:500]
        raise RuntimeError(f"ffmpeg failed (rc={proc.returncode}): {err}")

    if not dest.exists() or dest.stat().st_size == 0:
        raise RuntimeError(f"ffmpeg produced no output at {dest}")

    return dest


class VideoContinuityManagerSkill(SkillCallable):
    """Extracts last-frame anchor from a generated clip for next-clip seeding.

    SkillCallable contract:
    - params: {"video_path": str, "output_dir": str | None, "label": str | None}
    - data: {"continuity_frame_path": str, "source_video": str}
    - fallback: returns {"continuity_frame_path": None} marked is_fallback=True

    Designed to be called between two seedance_clips invocations during
    multi-clip pipeline runs (e.g., S5 60s = 4×15s).
    """

    name = "video-continuity-manager-skill"
    description = "Extracts the last frame of a clip as first-frame anchor for the next clip"
    max_retries = 2

    async def execute(self, params: dict[str, Any]) -> SkillResult:
        video_path = params.get("video_path")
        if not video_path:
            return SkillResult(
                success=False,
                error="video_path is required",
            )

        output_dir = params.get("output_dir")

        try:
            frame_path = await extract_last_frame(
                video_path=video_path,
                output_dir=output_dir,
            )
            return SkillResult(
                success=True,
                data={
                    "continuity_frame_path": str(frame_path),
                    "source_video": str(video_path),
                },
                metadata={"frame_bytes": os.path.getsize(frame_path)},
            )
        except (FileNotFoundError, RuntimeError) as exc:
            logger.warning(
                "video_continuity: extraction failed",
                video_path=str(video_path),
                error=str(exc)[:200],
            )
            return SkillResult(
                success=False,
                error=str(exc),
            )

    def validate_params(self, params: dict[str, Any]) -> list[str]:
        errors: list[str] = []
        vp = params.get("video_path")
        if not vp:
            errors.append("video_path is required")
        elif not isinstance(vp, (str, Path)):
            errors.append(f"video_path must be str or Path, got {type(vp).__name__}")
        return errors

    def validate_output(self, data: Any) -> list[str]:
        errors: list[str] = []
        if not isinstance(data, dict):
            errors.append(f"data must be dict, got {type(data).__name__}")
            return errors
        if "continuity_frame_path" not in data:
            errors.append("missing continuity_frame_path key")
        else:
            path = data["continuity_frame_path"]
            if path is not None and not Path(path).exists():
                errors.append(f"continuity_frame_path does not exist: {path}")
        return errors

    def fallback(self, params: dict[str, Any]) -> SkillResult:
        """Deterministic fallback: signal no-continuity to next clip.

        When extraction fails, the next clip will generate without a
        first-frame anchor (text-to-video instead of image-to-video). This
        is the SAME behavior as a single-clip pipeline pre-Sprint-1 — safe
        degradation rather than halt.
        """
        return SkillResult(
            success=True,
            data={
                "continuity_frame_path": None,
                "source_video": str(params.get("video_path", "")),
            },
            metadata={"fallback_reason": "extraction_failed"},
        )


try:
    SkillRegistry.register(VideoContinuityManagerSkill())
    logger.info("video_continuity_manager_skill: registered")
except ValueError:
    pass
